#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
#
# Add icons of general interest
#
/control/execute icons.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run "beamOn 10" "/run/beamOn 10"
/gui/addButton run "beamOn 30" "/run/beamOn 30"
/gui/addButton run "beamOn 100" "/run/beamOn 100"
/gui/addButton run run1 "/control/execute run1.mac"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "100 keV"  "/gun/energy 100 keV"
/gui/addButton gun "0.5 MeV"  "/gun/energy 0.5 MeV"
/gui/addButton gun "1 MeV"  "/gun/energy 1 MeV"
/gui/addButton gun "2 MeV"  "/gun/energy 2 MeV"
/gui/addButton gun "3 MeV"   "/gun/energy 3 MeV"
/gui/addButton gun "7 MeV"  "/gun/energy 7 MeV"
/gui/addButton gun "30 MeV"  "/gun/energy 30 MeV"
/gui/addButton gun "100 MeV"  "/gun/energy 100 MeV"
/gui/addButton gun "1000 MeV"  "/gun/energy 1000 MeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "e+"      "/gun/particle e+"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
/gui/addButton gun "gamma"   "/gun/particle gamma"
/gui/addButton gun "muon+"   "/gun/particle mu+"
/gui/addButton gun "muon-"   "/gun/particle mu-"
#
# Field menu :
/gui/addMenu field Field
/gui/addButton field "off"       "/globalField/setValue 0   0 0 tesla"
/gui/addButton field "0.2 tesla" "/globalField/setValue 0.2 0 0 tesla"
/gui/addButton field "2.0 tesla" "/globalField/setValue 2.0 0 0 tesla"
#
# Vis menu :
/gui/addMenu vis Vis
/gui/addButton vis DAWNFILE  "/control/execute visTutor/exN03Vis0.mac"
/gui/addButton vis OpenInventor "/control/execute visTutor/exN03Vis5.mac"
/gui/addButton vis TimeSlicing "/control/execute visTutor/exN03Vis12.mac"
/gui/addButton vis EmShower "/control/execute visTutor/exN03Vis13.mac"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wireframe"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# User defined icon :
#/gui/addIcon "Run beam on" user_icon "/run/beamOn 1" run.png 
